#gcc -o EscenaFinal EscenaFinal.cpp -lGLU -lGL -lglut -lm
#./EscenaFinal
g++ -c tgaload.cpp -lGLU -lGL -lglut -lm 
g++ -c EscenaFinal.cpp -lGLU -lGL -lglut -lm 
g++ -o EscenaFinal tgaload.o EscenaFinal.o -lGLU -lGL -lglut -lm -w
./EscenaFinal
