gcc -o bouncingballs bouncingballs.cpp -lGLU -lGL -lglut
gcc -o colorcube colorcube.cpp -lGLU -lGL -lglut
gcc -o cometride cometride.cpp -lGLU -lGL -lglut
gcc -o robotarm robotarm.cpp -lGLU -lGL -lglut
gcc -o sierpinski3d sierpinski3d.cpp -lGLU -lGL -lglut
gcc -o spinningsquare spinningsquare.cpp -lGLU -lGL -lglut
gcc -o tetrahedron tetrahedron.cpp -lGLU -lGL -lglut
gcc -o triangle triangle.cpp -lGLU -lGL -lglut


